import {
  Book,
  BookOpen,
  Briefcase,
  Coffee,
  Dumbbell,
  Film,
  Fuel,
  Gift,
  Home,
  Laptop,
  LineChart,
  LucideIcon,
  Package,
  Phone,
  ShoppingCart,
  Stethoscope,
  TrendingUp,
  Utensils,
  Wallet,
  Wifi,
  Zap,
} from "lucide-react-native";

export interface Entry {
  id: string;
  title: string;
  createdAt: Date;
  amount: number;
  icon: LucideIcon;
  paymentSystem:
    | "KPay"
    | "Wave"
    | "Visa Card"
    | "MasterCard"
    | "Cash"
    | "PayPal"
    | "Mobile Banking";
  type: "expense" | "income";
}

export const entriesDummy: Entry[] = [
  {
    id: "1",
    title: "Groceries",
    createdAt: new Date("2024-01-15T10:30:00Z"),
    amount: 85.5,
    icon: ShoppingCart,
    paymentSystem: "Cash",
    type: "expense",
  },
  {
    id: "2",
    title: "Electricity Bill",
    createdAt: new Date("2024-01-14T14:20:00Z"),
    amount: 120.75,
    icon: Zap,
    paymentSystem: "KPay",
    type: "expense",
  },
  {
    id: "3",
    title: "Salary Deposit",
    createdAt: new Date("2024-01-14T09:00:00Z"),
    amount: 2500.0,
    icon: Wallet,
    paymentSystem: "Mobile Banking",
    type: "income",
  },
  {
    id: "4",
    title: "Restaurant Dinner",
    createdAt: new Date("2024-01-13T19:45:00Z"),
    amount: 65.25,
    icon: Utensils,
    paymentSystem: "Visa Card",
    type: "expense",
  },
  {
    id: "5",
    title: "Freelance Payment",
    createdAt: new Date("2024-01-13T11:20:00Z"),
    amount: 500.0,
    icon: Laptop,
    paymentSystem: "Wave",
    type: "income",
  },
  {
    id: "6",
    title: "Movie Tickets",
    createdAt: new Date("2024-01-12T20:15:00Z"),
    amount: 45.0,
    icon: Film,
    paymentSystem: "KPay",
    type: "expense",
  },
  {
    id: "7",
    title: "Online Course Sale",
    createdAt: new Date("2024-01-12T15:30:00Z"),
    amount: 89.99,
    icon: BookOpen,
    paymentSystem: "PayPal",
    type: "income",
  },
  {
    id: "8",
    title: "Gas Station",
    createdAt: new Date("2024-01-11T08:45:00Z"),
    amount: 55.8,
    icon: Fuel,
    paymentSystem: "MasterCard",
    type: "expense",
  },
  {
    id: "9",
    title: "Investment Dividend",
    createdAt: new Date("2024-01-10T12:00:00Z"),
    amount: 150.25,
    icon: TrendingUp,
    paymentSystem: "Mobile Banking",
    type: "income",
  },
  {
    id: "10",
    title: "Internet Bill",
    createdAt: new Date("2024-01-10T10:30:00Z"),
    amount: 79.99,
    icon: Wifi,
    paymentSystem: "KPay",
    type: "expense",
  },
  {
    id: "11",
    title: "Coffee Shop",
    createdAt: new Date("2024-01-09T09:15:00Z"),
    amount: 18.5,
    icon: Coffee,
    paymentSystem: "Cash",
    type: "expense",
  },
  {
    id: "12",
    title: "Consulting Fee",
    createdAt: new Date("2024-01-08T16:30:00Z"),
    amount: 300.0,
    icon: Briefcase,
    paymentSystem: "Wave",
    type: "income",
  },
  {
    id: "13",
    title: "Amazon Purchase",
    createdAt: new Date("2024-01-08T14:20:00Z"),
    amount: 42.25,
    icon: Package,
    paymentSystem: "Visa Card",
    type: "expense",
  },
  {
    id: "14",
    title: "Stock Market Profit",
    createdAt: new Date("2024-01-07T11:00:00Z"),
    amount: 175.5,
    icon: LineChart,
    paymentSystem: "Mobile Banking",
    type: "income",
  },
  {
    id: "15",
    title: "Phone Bill",
    createdAt: new Date("2024-01-07T09:45:00Z"),
    amount: 35.99,
    icon: Phone,
    paymentSystem: "KPay",
    type: "expense",
  },
  {
    id: "16",
    title: "Gym Membership",
    createdAt: new Date("2024-01-06T07:30:00Z"),
    amount: 29.99,
    icon: Dumbbell,
    paymentSystem: "Cash",
    type: "expense",
  },
  {
    id: "17",
    title: "Bonus Payment",
    createdAt: new Date("2024-01-05T13:15:00Z"),
    amount: 1000.0,
    icon: Gift,
    paymentSystem: "Mobile Banking",
    type: "income",
  },
  {
    id: "18",
    title: "Book Store",
    createdAt: new Date("2024-01-04T16:45:00Z"),
    amount: 28.75,
    icon: Book,
    paymentSystem: "MasterCard",
    type: "expense",
  },
  {
    id: "19",
    title: "Rental Income",
    createdAt: new Date("2024-01-03T10:00:00Z"),
    amount: 800.0,
    icon: Home,
    paymentSystem: "Wave",
    type: "income",
  },
  {
    id: "20",
    title: "Medical Checkup",
    createdAt: new Date("2024-01-02T11:30:00Z"),
    amount: 120.0,
    icon: Stethoscope,
    paymentSystem: "KPay",
    type: "expense",
  },
];
